### ISSUE TITLE
CLI supports M1 Macs

### ISSUE THREAD

**Issue by sinchang** [zcong1993/homebrew-tap#1]
Thank you for building leetcode-tool.

But it seems doesn't work well on M1 Mac, could you support that?

<img width="721" alt="image" src="https://user-images.githubusercontent.com/3297859/140629316-f606784c-ef91-469c-a12c-5ea8312ed037.png">

**Comment by zcong1993** [comment]
I added arch arm64 for M1 mac, you can try to install it now. Feel free to give a feedback later cause I am not a  M1 mac user.

**Comment by sinchang** [comment]
Thanks in deed. It works well.
